# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYTWhPH1731-1JBcmFg8JZHeiJD8rwtw
"""

import numpy as np

# Definir la matriz aumentada del sistema de ecuaciones
A = np.array([
    [1, 0, 1, 2.5],
    [3, 4, 3, 11.5],
    [4, 1, 0, 15]
], dtype=float)

# Función para aplicar el método de Gauss-Jordan
def gauss_jordan(A):
    n = len(A)

    for i in range(n):
        # Hacer que el elemento A[i][i] sea 1
        A[i] = A[i] / A[i][i]

        # Hacer ceros en las demás posiciones de la columna
        for j in range(n):
            if i != j:
                A[j] = A[j] - A[j][i] * A[i]

    return A

# Aplicar Gauss-Jordan a la matriz aumentada
solucion = gauss_jordan(A)

# Imprimir las soluciones
print("Soluciones:")
for i in range(len(solucion)):
    print(f"x{i+1} = {solucion[i][-1]}")